# Generated by Django 3.1.3 on 2020-12-11 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MeetmeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Updated on'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
