# Generated by Django 3.1.3 on 2020-12-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeetmeApp', '0002_auto_20201211_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='modified',
        ),
    ]
